name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js 22.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'npm'
    - run: npm ci
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  test-node:
    name: Test (Node.js ${{ matrix.node-version }})
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v6
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --ignore-scripts
    - run: npm run test:node

  test-browser:
    name: Test (Browser/Chromium)
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'npm'
    - run: npm ci --ignore-scripts
    - run: npx playwright install --with-deps chromium
    - run: npm run test:browser

  test-coverage:
    name: Test coverage
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - name: Use Node.js 24.x
      uses: actions/setup-node@v6
      with:
        node-version: 24.x
        cache: 'npm'
    - run: npm ci --ignore-scripts
    - run: npm run test:coverage
